# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.destroy_all
GradeLevel.destroy_all
GradeSubject.destroy_all
Lesson.destroy_all
Comment.destroy_all

User.create(username: "eklimowich", password: "e", first_name: "Eric", last_name: "Klimowich", grade_teaching: "1st", subject_teaching: "ELA")
User.create(username: "mkuriscak", password: "m", first_name: "Mike", last_name: "Kuriscak", grade_teaching: "4th", subject_teaching: "Math")

GradeLevel.create(grade: "K", user_id: 1)
GradeLevel.create(grade: "1st", user_id: 1)
GradeLevel.create(grade: "2nd", user_id: 1)
GradeLevel.create(grade: "3rd", user_id: 2)
GradeLevel.create(grade: "4th", user_id: 2)

GradeSubject.create(subject: "ELA", grade_level_id: 1)
GradeSubject.create(subject: "Math", grade_level_id: 1)
GradeSubject.create(subject: "Science", grade_level_id: 1)
GradeSubject.create(subject: "Social Studies", grade_level_id: 1)
GradeSubject.create(subject: "Art", grade_level_id: 1)
GradeSubject.create(subject: "Music", grade_level_id: 1)
GradeSubject.create(subject: "PE", grade_level_id: 1)
GradeSubject.create(subject: "ELA", grade_level_id: 2)
GradeSubject.create(subject: "Math", grade_level_id: 2)
GradeSubject.create(subject: "Science", grade_level_id: 2)
GradeSubject.create(subject: "Social Studies", grade_level_id: 2)
GradeSubject.create(subject: "Art", grade_level_id: 2)
GradeSubject.create(subject: "Music", grade_level_id: 2)
GradeSubject.create(subject: "PE", grade_level_id: 2)
GradeSubject.create(subject: "ELA", grade_level_id: 3)
GradeSubject.create(subject: "Math", grade_level_id: 3)
GradeSubject.create(subject: "Science", grade_level_id: 3)
GradeSubject.create(subject: "Social Studies", grade_level_id: 3)
GradeSubject.create(subject: "Art", grade_level_id: 3)
GradeSubject.create(subject: "Music", grade_level_id: 3)
GradeSubject.create(subject: "PE", grade_level_id: 3)
GradeSubject.create(subject: "ELA", grade_level_id: 4)
GradeSubject.create(subject: "Math", grade_level_id: 4)
GradeSubject.create(subject: "Science", grade_level_id: 4)
GradeSubject.create(subject: "Social Studies", grade_level_id: 4)
GradeSubject.create(subject: "Art", grade_level_id: 4)
GradeSubject.create(subject: "Music", grade_level_id: 4)
GradeSubject.create(subject: "PE", grade_level_id: 4)
GradeSubject.create(subject: "ELA", grade_level_id: 5)
GradeSubject.create(subject: "Math", grade_level_id: 5)
GradeSubject.create(subject: "Science", grade_level_id: 5)
GradeSubject.create(subject: "Social Studies", grade_level_id: 5)
GradeSubject.create(subject: "Art", grade_level_id: 5)
GradeSubject.create(subject: "Music", grade_level_id: 5)
GradeSubject.create(subject: "PE", grade_level_id: 5)

Lesson.create(title: "Reading Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #1", file: "File 1", times_used: 1, grade_subject_id: 1)
Lesson.create(title: "Writing Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #2", file: "File 2", times_used: 1, grade_subject_id: 1)
Lesson.create(title: "Math Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #3", file: "File 3", times_used: 1, grade_subject_id: 2)
Lesson.create(title: "Arithmetic Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #4", file: "File 4", times_used: 1, grade_subject_id: 2)
Lesson.create(title: "Science Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #5", file: "File 5", times_used: 1, grade_subject_id: 3)
Lesson.create(title: "Geology Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #6", file: "File 6", times_used: 1, grade_subject_id: 3)
Lesson.create(title: "History Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #7", file: "File 7", times_used: 1, grade_subject_id: 4)
Lesson.create(title: "Government Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #8", file: "File 8", times_used: 1, grade_subject_id: 4)
Lesson.create(title: "Painting Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #9", file: "File 9", times_used: 1, grade_subject_id: 5)
Lesson.create(title: "Drawing Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #10", file: "File 10", times_used: 1, grade_subject_id: 5)
Lesson.create(title: "Singing Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #11", file: "File 11", times_used: 1, grade_subject_id: 6)
Lesson.create(title: "Beats Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #12", file: "File 12", times_used: 1, grade_subject_id: 6)
Lesson.create(title: "Sports Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #13", file: "File 13", times_used: 1, grade_subject_id: 7)
Lesson.create(title: "Health Lesson - K", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #14", file: "File 14", times_used: 1, grade_subject_id: 7)
Lesson.create(title: "Reading Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #15", file: "File 15", times_used: 1, grade_subject_id: 8)
Lesson.create(title: "Writing Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #16", file: "File 16", times_used: 1, grade_subject_id: 8)
Lesson.create(title: "Math Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #17", file: "File 17", times_used: 1, grade_subject_id: 9)
Lesson.create(title: "Arithmetic Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #18", file: "File 18", times_used: 1, grade_subject_id: 9)
Lesson.create(title: "Science Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #19", file: "File 19", times_used: 1, grade_subject_id: 10)
Lesson.create(title: "Geology Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #20", file: "File 20", times_used: 1, grade_subject_id: 10)
Lesson.create(title: "History Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #21", file: "File 21", times_used: 1, grade_subject_id: 11)
Lesson.create(title: "Government Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #22", file: "File 22", times_used: 1, grade_subject_id: 11)
Lesson.create(title: "Painting Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #23", file: "File 23", times_used: 1, grade_subject_id: 12)
Lesson.create(title: "Drawing Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #24", file: "File 24", times_used: 1, grade_subject_id: 12)
Lesson.create(title: "Singing Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #25", file: "File 25", times_used: 1, grade_subject_id: 13)
Lesson.create(title: "Beats Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #26", file: "File 26", times_used: 1, grade_subject_id: 13)
Lesson.create(title: "Sports Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #27", file: "File 27", times_used: 1, grade_subject_id: 14)
Lesson.create(title: "Health Lesson - 1st", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #28", file: "File 28", times_used: 1, grade_subject_id: 14)
Lesson.create(title: "Reading Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #29", file: "File 29", times_used: 1, grade_subject_id: 15)
Lesson.create(title: "Writing Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #30", file: "File 30", times_used: 1, grade_subject_id: 15)
Lesson.create(title: "Math Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #31", file: "File 31", times_used: 1, grade_subject_id: 16)
Lesson.create(title: "Arithmetic Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #32", file: "File 32", times_used: 1, grade_subject_id: 16)
Lesson.create(title: "Science Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #33", file: "File 33", times_used: 1, grade_subject_id: 17)
Lesson.create(title: "Geology Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #34", file: "File 34", times_used: 1, grade_subject_id: 17)
Lesson.create(title: "History Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #35", file: "File 35", times_used: 1, grade_subject_id: 18)
Lesson.create(title: "Government Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #36", file: "File 36", times_used: 1, grade_subject_id: 18)
Lesson.create(title: "Painting Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #37", file: "File 37", times_used: 1, grade_subject_id: 19)
Lesson.create(title: "Drawing Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #38", file: "File 38", times_used: 1, grade_subject_id: 19)
Lesson.create(title: "Singing Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #39", file: "File 39", times_used: 1, grade_subject_id: 20)
Lesson.create(title: "Beats Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #40", file: "File 40", times_used: 1, grade_subject_id: 20)
Lesson.create(title: "Sports Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #41", file: "File 41", times_used: 1, grade_subject_id: 21)
Lesson.create(title: "Health Lesson - 2nd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #42", file: "File 42", times_used: 1, grade_subject_id: 21)
Lesson.create(title: "Reading Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #43", file: "File 43", times_used: 1, grade_subject_id: 22)
Lesson.create(title: "Writing Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #44", file: "File 44", times_used: 1, grade_subject_id: 22)
Lesson.create(title: "Math Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #45", file: "File 45", times_used: 1, grade_subject_id: 23)
Lesson.create(title: "Arithmetic Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #46", file: "File 46", times_used: 1, grade_subject_id: 23)
Lesson.create(title: "Science Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #47", file: "File 47", times_used: 1, grade_subject_id: 24)
Lesson.create(title: "Geology Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #48", file: "File 48", times_used: 1, grade_subject_id: 24)
Lesson.create(title: "History Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #49", file: "File 49", times_used: 1, grade_subject_id: 25)
Lesson.create(title: "Government Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #50", file: "File 50", times_used: 1, grade_subject_id: 25)
Lesson.create(title: "Painting Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #51", file: "File 51", times_used: 1, grade_subject_id: 26)
Lesson.create(title: "Drawing Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #52", file: "File 52", times_used: 1, grade_subject_id: 26)
Lesson.create(title: "Singing Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #53", file: "File 53", times_used: 1, grade_subject_id: 27)
Lesson.create(title: "Beats Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #54", file: "File 54", times_used: 1, grade_subject_id: 27)
Lesson.create(title: "Sports Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #55", file: "File 55", times_used: 1, grade_subject_id: 28)
Lesson.create(title: "Health Lesson - 3rd", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #56", file: "File 56", times_used: 1, grade_subject_id: 28)
Lesson.create(title: "Reading Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #57", file: "File 57", times_used: 1, grade_subject_id: 29)
Lesson.create(title: "Writing Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #58", file: "File 58", times_used: 1, grade_subject_id: 29)
Lesson.create(title: "Math Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #59", file: "File 59", times_used: 1, grade_subject_id: 30)
Lesson.create(title: "Arithmetic Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #60", file: "File 60", times_used: 1, grade_subject_id: 30)
Lesson.create(title: "Science Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #61", file: "File 61", times_used: 1, grade_subject_id: 31)
Lesson.create(title: "Geology Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #62", file: "File 62", times_used: 1, grade_subject_id: 31)
Lesson.create(title: "History Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #63", file: "File 63", times_used: 1, grade_subject_id: 32)
Lesson.create(title: "Government Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #64", file: "File 64", times_used: 1, grade_subject_id: 32)
Lesson.create(title: "Painting Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #65", file: "File 65", times_used: 1, grade_subject_id: 33)
Lesson.create(title: "Drawing Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #66", file: "File 66", times_used: 1, grade_subject_id: 33)
Lesson.create(title: "Singing Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #67", file: "File 67", times_used: 1, grade_subject_id: 34)
Lesson.create(title: "Beats Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #68", file: "File 68", times_used: 1, grade_subject_id: 34)
Lesson.create(title: "Sports Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #69", file: "File 69", times_used: 1, grade_subject_id: 35)
Lesson.create(title: "Health Lesson - 4th", description: "This is a blurb talking all about the details and benefits of using Lesson Plan #70", file: "File 70", times_used: 1, grade_subject_id: 35)





Comment.create(content: "This is a comment about Lesson 1", rating: 4, user_id: 2, lesson_id: 1)
Comment.create(content: "This is a comment about Lesson 1", rating: 3, user_id: 2, lesson_id: 1)
Comment.create(content: "This is a comment about Lesson 3", rating: 3, user_id: 2, lesson_id: 3)

Comment.create(content: "This is a comment about Lesson 1", rating: 4, user_id: 1, lesson_id: 1)
Comment.create(content: "This is a comment about Lesson 2", rating: 2, user_id: 1, lesson_id: 2)
Comment.create(content: "This is a comment about Lesson 2", rating: 3, user_id: 1, lesson_id: 2)
